on:
  # Trigger the workflow on push or pull request
  pull_request:
    branches:
      - master
      - develop

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `👋 Thankyou for Making this PR and contributing to Hairify to enhance the product, we appreciate your time spent working on this and will be reviewing you PR soon.
                    Make Sure you have followed all the contributing guidelines and are not tagging maintainers continuously for a PR review.
                    If you Pull Request is incomplete at this state, make sure to mark it as draft.
              `     
            })
